### ISSUE TITLE
Need to provide instructions & key config info on final disc

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#129]
Thinking another MODE 7 loading screen with the keyboard layout and instructions just before the game enters MODE 2.  Could wait for a key press with timeout here.

Also need a README on the disc that provides extra info and a link back to the website etc.

**Comment by simondotm** [comment]
Should we do this in the 'classic' style? You know with a double height red/yellow BG/FG header and then the keys with a "press SPACE to start" type gig?

**Comment by kieranhj** [comment]
Added Manual.txt file to the disc (all 11K of it!)  Will look at doing a MODE 7 screeny...

**Comment by kieranhj** [comment]
Not sure I'm going to have time to design a MODE 7 screen, not my forte...

**Comment by kieranhj** [comment]
Made a 'classic' keys screen to start in a branch.  Would love to have a nice MODE 7 teletext intro sequence with nice instructions and manual etc. but not going to happen in time.  There is a text copy of the original manual on the disc with instructions to *TYPE it.

**Comment by kieranhj** [comment]
This is in.  Just need a README with our info on it.

**Comment by inversephase** [comment]
if the user waits long enough at the keys screen the game keeps loading despite press any key. at least let it wait an exhaustive amount of time (4-5 times as long as it does now) =]

**Comment by kieranhj** [comment]
Changed to 30 seconds in Release.

**Comment by kieranhj** [comment]
Added draft README but seems more important to put the details on the web rather than in the disc image.
