### ISSUE TITLE
Danger ditty should play as the player hits the ground on level 1

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#137]
At the moment the "danger" ditty tune plays as soon as it is cued during loading of level 1.  On Apple II the cue isn't picked up until the game starts ticking so is triggered on the first frame of gameplay to coincide with the player's unceremonious entrance.

**Comment by simondotm** [comment]
I noticed that, thought it was just an artefact from how we load stuff.

**Comment by kieranhj** [comment]
Fixed in branch.

**Comment by kieranhj** [comment]
In master.
