### ISSUE TITLE
Make.bat suggestions

### ISSUE THREAD

**Issue by simondotm** [kieranhj/pop-beeb#149]
Make.bat wont work on my system because I have BeebAsm somewhere different.
How amenable are we to assuming it is on the users PATH and removing the ..\\..\\bin\\ bit?
Also, since I use VS code, I dont need to redirect output to compile.txt - any objections if we dont do that?

**Comment by kieranhj** [comment]
Err, yes we should reconcile our build systems!

I copied BeebAsm.exe into the pop-beeb bin folder as we might as well carry the assembler version with us. (It would have been nice to use features from v1.09 but wanted broadest compatibility hence still using v1.08)

There are a number of operations done in the make.bat file - can all these be run in VS Code? Was thinking not everyone would have that installed.

**Comment by kieranhj** [comment]
Going to close and merge with #123 for after release.

**Comment by simondotm** [comment]
Works ok for me now that BeebAsm is locally referenced.
