### ISSUE TITLE
Use the Bitshifters load logo with "Prince Of Persia" text on it

### ISSUE THREAD

**Issue by simondotm** [kieranhj/pop-beeb#150]
If you like. More acornsoft-y that way.
For extra XP points reveal the logo from top to bottom slightly slower, as if it was the original BASIC acornsoft loader that poked memory from PAGE+N bytes to &7C00 ... :)

**Comment by kieranhj** [comment]
I was going to change it but wanted the box surrounding the text to be rounded...

**Comment by simondotm** [comment]
Added, can be tweaked further if need be.
