### ISSUE TITLE
Missing new CHTAB6.B sprite set for cutscenes

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#17]
The Princess & Epilog cutscenes etc. are not yet implemented.
Requires loading of temporary character sprite sets from disc and replacing afterwards.
Also requires loading a hires screen from disc (I think?) that isn't included in the repo (unless this comes from a different level? - need to find out :)

**Comment by kieranhj** [comment]
Nearly done - don't think it's loading the right CHTAB6 for later scenes yet.

**Comment by kieranhj** [comment]
Also Princess's room screen is just loaded from disc twice for each screen buffer - this is ugly and slow.

**Comment by kieranhj** [comment]
Princess room screen now copied RAM to RAM not loaded twice.

**Comment by kieranhj** [comment]
Correct CHTAB6A/B now loaded for levels >3.  Just need music & Princess screen from John.

**Comment by kieranhj** [comment]
Have Princess screen from John!

**Comment by simondotm** [comment]
See also #79

**Comment by kieranhj** [comment]
Going to close this as still missing other new sprite sets from Dethmunk. See #28.
