### ISSUE TITLE
May need an event driven sequence clock for attract mode

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#171]
At the moment the attract mode is timed using a "pause for X seconds" function in between each part in the sequence and is based on b-em with disc drivev noises turned off (slightly faster.)

Unfortuntely any load operation is blocking and can take a hugely variable amount of time, depending on whether it is real floppy drive hardware (~4K/s) or a modern MMC interface (~100K/s).

It would be better to drive a real-time sequence clock under events and then have a "wait until sequence clock has passed X:XX" function to gate when each part is triggered.

**Comment by kieranhj** [comment]
Started in branch.

**Comment by inversephase** [comment]
I pretty much have nothing other than an emulator to judge this by but would be happy to check out a video to gauge whether I feel like anything is severely off

**Comment by kieranhj** [comment]
In master.  Tested in b-em w/ and w/out disc drive noises.  Will test on fast DC device soon.
