### ISSUE TITLE
Blank screen at end of cut scenes?

### ISSUE THREAD

**Issue by simondotm** [kieranhj/pop-beeb#178]
Currently the cut scenes freeze on completion while the level is loaded.
Polish might be to blank screen at end of cut scene.

**Comment by kieranhj** [comment]
Hmm, I thought it used to do this, maybe I broke it?

**Comment by kieranhj** [comment]
Oops, no you are correct - the Apple II code for blanking the screen was commented out of the beginning of the RESTART fn in topctrl.asm.  It needs to be replaced with a simple call to beeb_hide_screen fn.
