### ISSUE TITLE
Check the attract sequence timings again vs PC version

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#182]
Change to cutscene playback during music might have thrown the timings out a tiny bit
Never did check the cutscene against the PC version properly anyway...

**Comment by inversephase** [comment]
I will say (I think this is an A2-vs-later version difference) that there is an extended pause when jaffar reaches out to the princess that is not in our version, and I always kind of wondered about it

**Comment by inversephase** [comment]
story4 is definitely cut off by story5. if I had to wager a guess, it's about 15 frames

**Comment by kieranhj** [comment]
Done.  Sounds good to me and the story cutscene is better paced.

**Comment by kieranhj** [comment]
*not in master yet.
