### ISSUE TITLE
Unknown sprite corruption & crash bug occured on level 8

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#189]
Whilst playing level 8 on real HW, I went right from the start screen and drank the bad potion.  After this certain sprites were corrupted (long jump, fighting frames) and after I died the level reload failed.  Unfortunately there was no PC on the screen so couldn't debug this.

Did not repeat after reloading save game from start of level 8.  :(

**Comment by inversephase** [comment]
clearly, you were not supposed to drink that

**Comment by kieranhj** [comment]
Played through to level 9 on real HW today and didn't encounter this.  I have also made a change so that the screen is forceably displayed on crash so we can maybe glean something next time.

**Comment by kieranhj** [comment]
Second day of play through and didn't experience this again. Hmmm.

**Comment by kieranhj** [comment]
I bet this is the stack overfow issue as the graphics are unpacked to the stack... this would also cause the level load to fail. Now fixed with v1.1.
