### ISSUE TITLE
Attract mode not finished

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#19]
Attract mode - intro sequence, title screen, credits, music, autoplay of demo level - etc. not yet implemented.

**Comment by kieranhj** [comment]
The sequence flow is implemented but still missing music and nice wipes between double hi-res screens.

**Comment by simondotm** [comment]
See also #79

**Comment by kieranhj** [comment]
Need to check all the timings for the various screens in attact sequence.  On Apple II these were dictated by the length of the tune for each one.  Our music works differently.

**Comment by kieranhj** [comment]
Need to also be sensitive to the loading speed of different devices.  MMC will load a MODE 2 screen almost instantly whilst a real floppy will take at least a couple of seconds.  At the moment the attract sequence progresses too quickly on DC so music gets cut off.

**Comment by kieranhj** [comment]
Also need final Credits screen from Dethmunk.

**Comment by kieranhj** [comment]
Don't forget to put Bitshifters URL on the Credits screen.

**Comment by kieranhj** [comment]
New Credits screen in.

**Comment by inversephase** [comment]
just checking, we have all story music necessary, but I think there needs to be door creak noises, correct?

**Comment by inversephase** [comment]
doorcreak.vgm is in slack

**Comment by kieranhj** [comment]
Attract sequence is all in and timed to b-em w/out disc noises.  See #171 for improvement w/ other devices.

**Comment by inversephase** [comment]
need to replace m-story4 with m-story4-endsright =]

**Comment by kieranhj** [comment]
Now in master and sequenced with vsync ticker.
