### ISSUE TITLE
Versioning Releases

### ISSUE THREAD

**Issue by EndeavourAccuracy** [kieranhj/pop-beeb#197]
Looks like you're getting closer to release. Nice progress. I suggest giving releases, even if you'll release just once, a version number. One way would be to edit [VERSION.S](https://github.com/kieranhj/pop-beeb/blob/master/Source/VERSION.S#L9) to modify the Ctrl+v message, [similar to](https://github.com/NagyD/SDLPoP/blob/master/src/seg000.c#L601) SDLPoP. Another would be to modify the .ssd file signature, "POP BEEB", in the disc-template.ssd.bin, to include a version number, for example as "POPBEEBh" where h could start as 0x00.

**Comment by kieranhj** [comment]
The disc and code is already versioned.  I've just realised that the location of the version may move around so will just tweak this and let you know the version information format.

**Comment by EndeavourAccuracy** [comment]
> I've just realised that the location of the version may move around

I also noticed the starting offset of the levels has changed (compared to what you mentioned [here](https://github.com/kieranhj/pop-beeb/issues/139#issuecomment-374903328)). Probably simply because you're still moving blocks around, for optimization purposes and such.

> so will just tweak this and let you know the version information format.

All right, thanks.

**Comment by EndeavourAccuracy** [comment]
Looked into it myself.
0x26F0 has 1 byte for the version, e.g. 0x10 is version 1.0
0x26F1 has 7 bytes for the build, e.g. 0x18 0x03 0x29 0x22 0x00 0x6B 0x63 is build 180329.2200kc (ddmmyy.hhmmuu)
