### ISSUE TITLE
Enable Music/sound/volume related keys in title sequences

### ISSUE THREAD

**Issue by simondotm** [kieranhj/pop-beeb#198]
At the moment pressing any key during intro/attract will exit to game.
Not sure if the music/sound/volume key detection code runs during the titles, but it would be nice to be able to adjust volume or turn music on/off in title screens without triggering a game load.

**Comment by kieranhj** [comment]
There are a few places the keys are checked because could be in a cutscene but I'll take a quick look later on.

**Comment by kieranhj** [comment]
Couple of challenges - the key detection code just immediately breaks out and calls "start game" in the various places it is used.  Also, because the frame buffer alignment is different in attract, we'd need separate fns to write messages to the screen.

**Comment by kieranhj** [comment]
Hmmm, in theory MUSICKEYS fn in specialk.asm is supposed to handle keyboard input whilst music is playing but might not catch all cases.

**Comment by simondotm** [comment]
I saw that function, I suspect it needs looking at because we mute the psg in the other check for ksound and kmusic toggles, but not here.

**Comment by kieranhj** [comment]
The music on/off key combo does work here during attract (but has the psg hangover) but not volume.

**Comment by kieranhj** [comment]
Fix this so on/off & volume work in cutscenes.  Only place it doesn't work is the demo level.
