### ISSUE TITLE
Should Epilog do anything more interesting?

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#199]
Original Apple II "win" music was only around 20 seconds so just showed Epilog text and then cut to splash before rebooting.

The PC "win" music is 2 full minutes and (currently) cannot be skipped with a key press (!!)  Might be possible to provide some more interest to the user by cycling some of the attract screens...

**Comment by inversephase** [comment]
the second minute of the two-minute "won" tune from PC is basically repeated; I can cut it back down to 1 so there is no repeated data.

that said, I think this might be a good opportunity to run some credits, or (this would probably take some work but) do a cast&crew eg. "starring: prince, guard guy, jaffar, etc"

**Comment by kieranhj** [comment]
At current rate of progress & memory, prognosis is - "unlikely".

**Comment by inversephase** [comment]
what about throwing up the credits screen from the title sequence for 15-20 seconds before cutting to the scenery shot?

**Comment by kieranhj** [comment]
I'll take a look after everything else - not expecting many folks to get to the end for a while.  :)
