### ISSUE TITLE
Need a music system

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#25]
Need a way to play nice music
@simondotm has VGM versions of the PoP tunes and has offered to help porting the music player from our previous demos.
Resource allocation is 3.5K from ANDY RAM (eventually.)

**Comment by simondotm** [comment]
3.5K!! *breaks out dmf player wip*

**Comment by simondotm** [comment]
Getting there! :)

**Comment by simondotm** [comment]
Systems now in place. Closing.
