### ISSUE TITLE
Automatic build versioning on ssd image?

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#42]
Would be nice to have an automatic versioning system so that for any given ssd I know which build version is on there.  This would help keep track of any bug reports and addresses provided for exceptions etc.

**Comment by ZornsLemma** [comment]
Definitely not a perfect solution, but could you use the TIME$ support in the proposed-updates version of beebasm? Do "equs TIME$" somewhere in one of your source files, then you can see the timestamp in the binary with *DUMP. It's not a git commit ID or anything, but if you're the only active developer, there'd be a reasonable correlation between commit timestamps and build timestamps.

**Comment by ZornsLemma** [comment]
I guess the proper solution would be to have your makefile do something like: "git rev-parse HEAD >> revision.txt", and add 'PUTFILE "revision.txt", "REVIS"' to the source.

**Comment by kieranhj** [comment]
I worked out how to mangle %DATE% and %TIME% into a build string in my batch makefile.  Will load this into the game at some point.

**Comment by kieranhj** [comment]
First 8 bytes of the Core executable are now: $Vv $YY $MM $DD $HH $MM and first two letters of %USERNAME%.  Need to add a quite option to display this on CTRL-V.

**Comment by kieranhj** [comment]
In branch.

**Comment by kieranhj** [comment]
Done.  Press CTRL-V.
