### ISSUE TITLE
How much to disable the OS during gameplay?

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#54]
The OS is still receiving the vsync interupt during gameplay which can take a couple of scanlines to process.  Could disable this entirely but then this messes with disc loading IIRC.  Perhaps turn this on/off in custom irqv handler depending on application state?

**Comment by simondotm** [comment]
Could we just make our event handler not jump to the old event vector and see if that cocks anything up?

**Comment by kieranhj** [comment]
Yes, I think that would be safe.  I was pondering whether to move to IRQV1 and then only pass on the vsync when requiring disc access.  This smells like a potential bug farm given that you can hit savegame at any time.  I'm not sure that the OS hogging all our CPU is the problem here anyway.  😄

**Comment by kieranhj** [comment]
Yes, I think I've decided that we should continue to play nice with the OS.  Screen writes from the plot routines dominate any CPU time so not really worth messing and introducing potential bugs.
