### ISSUE TITLE
Kid dies in demo level playback!

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#75]
Must be something to do with the frame rate on Apple II vs Beeb.
Suggest waiting until all the perf and frame swap has been sorted.
Check DemoProg1 in auto.asm.

**Comment by simondotm** [comment]
Ha - I thought that was intentional! :)

**Comment by kieranhj** [comment]
LOL!  No, he is meant to make the jump then meet, fight and beat a guard on the next screen before exiting.

**Comment by kieranhj** [comment]
Fixed in demo build branch.  Noticed that he can lose the fight with the guard though - it's not scripted, the AI just fights but with different skill values...

**Comment by kieranhj** [comment]
PR'd.
