### ISSUE TITLE
Graphical glitch in Princess Room

### ISSUE THREAD

**Issue by simondotm** [kieranhj/pop-beeb#76]
![image](https://user-images.githubusercontent.com/7404321/36068084-89d2274c-0ec4-11e8-8c08-60472f68f719.png)

Seems to be a white block area on the princess screen - not sure if this is intentional or not.

**Comment by kieranhj** [comment]
Yep, that's a foreground sprite to cover the Vizier when he walks in - Dethmunk just needs to update the sprite image to match his lovely new MODE 2 screen and I will line it up in code.

**Comment by kieranhj** [comment]
New sprite from Dethmunk is better but not quite lined up...

**Comment by kieranhj** [comment]
Dethmunk has fixed this - currently in import-new-sprites branch, to be merged.

**Comment by kieranhj** [comment]
Fixed in early cutscenes, not later ones (yet.)

**Comment by kieranhj** [comment]
Same as #17
