### ISSUE TITLE
No sound effects play in the attract mode game demo

### ISSUE THREAD

**Issue by simondotm** [kieranhj/pop-beeb#79]
Not sure yet if this is a bug or by design...

**Comment by kieranhj** [comment]
Just watched the demo level in AppleWin and there is definitely sound.  I do get a sound when the player dies on the spikes on the current build but nothing else.

**Comment by simondotm** [comment]
Very strange, I wonder why there's no sound triggering then...

**Comment by kieranhj** [comment]
Fixed this in demo branch.  When an audio bank is loaded it kills the music player.  Sound effects rely on the music player being active to update.  Enabling the music player after bank load fixes this partially - when ending music early the vgm player didn't set the ended flag in deinit so could still pick up garbage data.  Now sorted and fixes a couple of other bugs as well I think.

**Comment by kieranhj** [comment]
PR'd.
