### ISSUE TITLE
Discuss Music strategy 

### ISSUE THREAD

**Issue by simondotm** [kieranhj/pop-beeb#82]
The game has a lot more music themes than we've currently implemented. At the moment the handful of SMS themes we have are mapped very approximately to the Apple original.
Decision/discussion is whether or not to produce new tunes. Memory will definitely be a constraint however for in-game music, since we only have 4K for all SFX and music.
Its possible to load audio banks on demand for the various cut scenes however.

**Comment by kieranhj** [comment]
Current strategy is for IP to reauthor all of the PC tunes.  We have a mapping to Apple II enums, just about.
