### ISSUE TITLE
Make the screen flash effects change BG or FG only?

### ISSUE THREAD

**Issue by simondotm** [kieranhj/pop-beeb#83]
Effect might be nicer if only BG/Black colour is flashed.
Eg. for health hit, just the BG changing red instead of whole palette?
Eg. for cut scene, just the FG changing white instead of whole palette?

**Comment by kieranhj** [comment]
This is as it works in the Apple II version - do you think it is a bit much?

**Comment by simondotm** [comment]
Its not bad per se, but would just be a bit of polish I think if only the BG or FG get flashed.

**Comment by kieranhj** [comment]
The beginning cutscene scene is supposed to flash 5 times (lightning) but just seems to stay solid.

**Comment by kieranhj** [comment]
Fixed lighting flash.

A modern game would have a photosensitivity warning at the start.  Could do this in MODE 7 during load?

**Comment by kieranhj** [comment]
I added bg only flash for when the weightless potion ends (flashes bg green.)  Trivial to change for the other FX.  Just need to make a call...

**Comment by kieranhj** [comment]
Might check the PC version actually as defacto.

**Comment by kieranhj** [comment]
PC version just flashes background.  I will change it to that when I get chance.

**Comment by kieranhj** [comment]
Fixed.
