### ISSUE TITLE
Missing attract screen?

### ISSUE THREAD

**Issue by simondotm** [kieranhj/pop-beeb#84]
![image](https://user-images.githubusercontent.com/7404321/36076397-7e935cc2-0f53-11e8-8a29-df8008e1736d.png)

Should attract sequence be?
Title -> Broderbund -> Copyright -> Title -> **"In the sultans absence..."** -> Cutscene -> "Marry Jaffar..."

**Comment by kieranhj** [comment]
Yes, it does load it but doesn't show it - I think I took the delay out but guessing there is no music to play over the screen so just goes straight to the Princess cutscene.

**Comment by simondotm** [comment]
Ah ok - I'm slowly trying to comprehend the "sound code", but it seems quite fragmented...

**Comment by kieranhj** [comment]
Yes, it was definitely put in towards the end - the code is stashed all over the place and had multiple versions of functions depending on whether it was being called from Main or Aux mem.  I moved some of it into audio.asm but not all of it.  The cutscenes are probably in subs.asm.

**Comment by kieranhj** [comment]
Lobbed in a delay so this appears.
