### ISSUE TITLE
Check SFX for spikes & gate - seem to be faulty?

### ISSUE THREAD

**Issue by simondotm** [kieranhj/pop-beeb#88]
the noise when the gate is finally all the way down is the same as the spikes coming up (I wrote FX2 to work for both of these, but gateslam would be way better for the gate being down)

**Comment by kieranhj** [comment]
This is correct behaviour vs the code.  GateDown is used for spikes appearing and for when a gate reaches the bottom at normal speed.  GateSlam is used for when a gate closes at high speed.
